// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: [
    'Introduction',
    'Examples',
    'In_Depth',
    {
      type: 'category',
      label: 'Packages',
      collapsed: false,
      items: [
        'packages/core',
        'packages/web-renderer',
        'packages/offline-renderer',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        'guides/Making_Sound',
        'guides/Understanding_Keys',
        'guides/Understanding_Memoization',
        'guides/Sample_Accurate_Rendering',
        'guides/Native_Integrations',
        'guides/Custom_Native_Nodes',
        'guides/Virtual_File_System',
      ],
    },
    {
      type: 'category',
      label: 'Core Library Reference',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'LibraryIndex',
      },
      items: [{
        type: 'autogenerated',
        dirName: 'reference',
      }],
    },
  ],
};

module.exports = sidebars;
